
FAIL test SyncAccessHandle.getSize after SyncAccessHandle.write promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
FAIL test createSyncAccessHandle.getSize with pending operation promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."

